## cartridge.properties for cartridge plugin_custom_api
#Wed Aug 30 0:20:26 CEST 2026
demandware.cartridges.plugin_custom_api.multipleLanguageStorefront=true
demandware.cartridges.plugin_custom_api.id=plugin_custom_api